# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KristenMcWilliam.UnitBargainHunter
PackageVersion: 0.1.0
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/Merrit/unit_bargain_hunter/releases/download/v0.1/UnitBargainHunter-windows-installer.exe
  InstallerSha256: E6A8460B2F68145D26AEE5058C9F20D1D61373D0D65BE40CF4992CD0A9A43512
ManifestType: installer
ManifestVersion: 1.0.0