# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: KristenMcWilliam.UnitBargainHunter
PackageVersion: 0.2.0
PackageLocale: en-US
Publisher: Kristen McWilliam
PackageName: Unit Bargain Hunter
License: GPL 3
ShortDescription: Easily compare items when shopping
ManifestType: defaultLocale
ManifestVersion: 1.0.0

