# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KristenMcWilliam.UnitBargainHunter
PackageVersion: 0.2.0
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/Merrit/unit_bargain_hunter/releases/download/v0.2.0/UnitBargainHunter-windows-installer.exe
  InstallerSha256: 1C114E813F901BC1791E3AACE0B718A9731BA2B0C310A20250E3F7F80181FEEF
ManifestType: installer
ManifestVersion: 1.0.0

