name: unit_bargain_hunter
description: "Easily compare items when shopping"
publish_to: "none"
version: 1.6.0+13

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.0.0-dev.9
  flutter_slidable: ^1.3.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^3.0.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.3
  in_app_purchase: ^3.0.2
  in_app_purchase_android: ^0.2.2+6
  intl: ^0.17.0
  logging: ^1.0.2
  path_provider: ^2.0.10
  pub_semver: ^2.0.0
  store_checker: ^1.0.0
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
  yaml: ^3.1.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: 312f340a607caf3f019ec883a7e684ac4bada0cf
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  msix: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/theme_switch/
    - pubspec.yaml

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_app_builder:
  app_display_name: "Unit Bargain Hunter"
  author: "Merritt Codes"
  identifier: codes.merritt.bargain
  msix_identity_name: 33694MerrittCodes.UnitBargainHunter
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icon\icon.png
  msix_capabilities: internetClient
