name: unit_bargain_hunter
description: "Easily compare items when shopping"
publish_to: "none"
version: 1.1.1+6

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  intl: ^0.17.0
  logging: ^1.0.2
  pub_semver: ^2.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.20
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81

dev_dependencies:
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: beb9bcc44075cb2bbf32642880f4d15e25a47b80
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  msix: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bio-photo.jpg
    - assets/images/theme_switch/
    - pubspec.yaml

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_app_builder:
  app_display_name: "Unit Bargain Hunter"
  author: "Kristen McWilliam"
  identifier: codes.merritt.bargain
  msix_icon_path: assets\icon\icon.png
