name: unit_bargain_hunter
description: "Easily compare items when shopping"
publish_to: "none"
version: 1.3.0+10

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.0.0-dev.5
  font_awesome_flutter: ^9.1.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.3
  in_app_purchase: ^3.0.2
  intl: ^0.17.0
  logging: ^1.0.2
  pub_semver: ^2.0.0
  store_checker: ^1.0.0
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81

dev_dependencies:
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: ba0032b98fc664d65dd808d6f0e5e088f5537c9e
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  msix: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/theme_switch/
    - pubspec.yaml

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_app_builder:
  app_display_name: "Unit Bargain Hunter"
  author: "Kristen McWilliam"
  identifier: codes.merritt.bargain
  msix_icon_path: assets\icon\icon.png
