name: unit_bargain_hunter
description: "Easily compare items when shopping"
publish_to: "none"
version: 1.15.0+22

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  badges: ^3.0.2
  bloc: ^8.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.0.0-dev.9
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.3.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: 7b120b8ef8ec9f70aa1a3e0f20707aae4e9e1a05
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^1.0.0
  in_app_purchase: ^3.0.7
  in_app_purchase_android: ^0.3.6
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^2.0.1
  multi_split_view: ^2.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.0.10
  pub_semver: ^2.0.0
  store_checker: ^1.0.0
  url_launcher: ^6.0.20
  uuid: ^4.4.2
  window_manager: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
  yaml: ^3.1.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.3.3
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: abe7d671ff5e5fc692bec8908285282a88d928c0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.4.2
  mocktail: ^1.0.4
  msix: ^3.5.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - pubspec.yaml

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter_app_builder:
  app_display_name: "Unit Bargain Hunter"
  author: "Merritt Codes"
  identifier: codes.merritt.bargain
  msix_identity_name: 33694MerrittCodes.UnitBargainHunter
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icon\icon.png
  msix_capabilities: internetClient
