name: unit_bargain_hunter
description: "Easily compare items when shopping"
publish_to: "none"
version: 0.2.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
  equatable: ^2.0.2
  flutter_bloc: ^7.0.1
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  pub_semver: ^2.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/theme_switch/
    - pubspec.yaml

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
