name: Build iOS version
on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: |
          flutter pub get
          flutter test
          flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: UnitBargainHunter-iOS
          path: /Users/runner/work/unit_bargain_hunter/unit_bargain_hunter/build/ios/iphoneos/Runner.app
