name: Build Android version
on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1.5.0
        with:
          channel: beta
      - run: |
          flutter pub get
          flutter test
          flutter build apk
          flutter build appbundle
          mv build/app/outputs/flutter-apk/app-release.apk build/UnitBargainHunter-android.apk
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/
      - uses: actions/upload-artifact@v2
        with:
          name: UnitBargainHunter-android.apk
          path: build/UnitBargainHunter-android.apk
